language: node_js
node_js:
- '0.10'
after_success:
# Automatically accept the host key authentication
- echo -e "Host *drush.in\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
# Set up git to know the user name
- git config --global user.name $GIT_NAME
- git config --global user.email $GIT_EMAIL
# Deploy if it's a Pull Request or a commit to master.
- if [ $TRAVIS_PULL_REQUEST == 'true' ] || [ $TRAVIS_BRANCH == "master" ]; then npm run deploy; fi
cache:
  directories:
  - node_modules
notifications:
  email: false
env:
  global:
  - GIT_NAME: Kala C. Bot
  - GIT_EMAIL: kalacommitbot@kalamuna.com

  # Encrypted Environment Variables
  # GIT_NAME: The name of the git user to use.
  # GIT_EMAIL: The email address for the git user.
  # GH_TOKEN: The personal token from https://github.com/settings/tokens/new .
  #
  # gem install travis
  # travis encrypt GIT_NAME="John Smith"
  # travis encrypt GIT_EMAIL="john@smith.com"
  # travis encrypt GH_TOKEN=fd0c12c7b959b423a18fa416a1d924f3fdf82824
  - secure: ZJBBX6XW3mnbVAS8zddDebDUw+CPmAfzmQGu/pb75ndvRM9WUAyWTq30eh513IcE0tqqRk075U6kYTs+tA2HNDsUXpnggIj2s1s1U26o+0k4Yqxg3Wme4AEyYhfzgMrAwAVJbpGHyGjuhBlNiMlym+w2dceDzCTpZahDxVstmv0=
